In [ ]:
import numpy as np

x = [1,2,3,4]

y = np.array([1,2,3,4,5])

print(y)
print(type(y))
print(y.ndim)

In [4]:
l = []
for i in range(1,5):
    int_l = int(input("enter: "))
    l.append(int_l)


print(np.array(l))

enter:  1
enter:  2
enter:  3
enter:  3


[1 2 3 3]


In [5]:
ar2 = np.array([[1,2,3,4],[1,2,4,3]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 4 3]]
2


In [9]:
 ar_zero =  np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)

print(ar_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
#ONES

In [11]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [18]:
#EMpty
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


In [15]:
#RANGE
ar_rn = np.arange(5)
print(ar_rn)

[0 1 2 3 4]


In [20]:
#ARITHMETIC OPERATIONS
var = np.array([1,2,3,4])
varadd = var + 3
print(var)
print("new array: ",varadd)

[1 2 3 4]
new array:  [4 5 6 7]


In [29]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1 + var2
print(varadd)

[2 4 6 8]


In [30]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = np.add(var1,var2)
varadd1 = np.add(var1,3)
print(varadd)
print(varadd1)

[2 4 6 8]
[4 5 6 7]


In [23]:
var = np.array([1,2,3,4])
varadd = var-3
print(varadd)

[-2 -1  0  1]


In [25]:
var = np.array([1,2,3,4])
varadd = var*3
print(varadd)

[ 3  6  9 12]


In [26]:
var = np.array([1,2,3,4])
varadd = var/3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [27]:
var = np.array([1,2,3,4])
varadd = var%3
print(varadd)

[1 2 0 1]


In [31]:
#2D ARRAY

In [33]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[1,2,3,4],[5,6,7,8]])

print(arr1)
print("+")
print(arr2)

var = arr1 + arr2
print()
print(var)

[[1 2 3 4]
 [5 6 7 8]]
+
[[1 2 3 4]
 [5 6 7 8]]

[[ 2  4  6  8]
 [10 12 14 16]]


In [41]:
#ARITHMETIC FUNCTIONS
var = np.array([1,6,8,3,78,3,0])

#tells min variable and it's position in array
print("min : ",np.min(var),np.argmin(var)) 
#tells max variable and it's position in array
print("max : ", np.max(var),np.argmax(var))
#finding square root
print("sqrt: ",np.sqrt(var))

min :  0 6
max :  78 4
sqrt:  [1.         2.44948974 2.82842712 1.73205081 8.83176087 1.73205081
 0.        ]


In [39]:
var1 = np.array([[2,1,3],[9,5,6]])

#axis=0 tells coloumns and axis=1 indiacates rows
print(np.min(var1, axis=0))

[2 1 3]
